# Generated by Django 4.0.4 on 2022-05-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField(max_length=255)),
                ('cuerpo', models.CharField(max_length=255)),
                ('valoracion', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
