# Generated by Django 4.0.4 on 2022-05-27 17:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmodel', '0003_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='valoracion',
        ),
        migrations.AlterField(
            model_name='reseña',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
