# Generated by Django 4.0.4 on 2022-05-27 22:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmodel', '0004_remove_reseña_valoracion_alter_reseña_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
    ]
