# Generated by Django 4.0.4 on 2022-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodel', '0006_reseña_tapa_alter_reseña_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='tapa',
            field=models.ImageField(blank=True, upload_to='tapas'),
        ),
    ]
